### ISSUE TITLE
Set correct content types

### ISSUE THREAD

**Issue by zelima** [datahq/planner#20]
As a datahub user, I want resources to have a correct content type (`application/zip`, `application/json`, etc..) instead of default `text/plain`, so that when I click it is not displayed as a text in the browser, but downloaded. 

## Acceptance Criteria 

* [ ] this zip resource is downloaded when clicked in Firefox https://pkgstore.datahub.io/core/cofog/datapackage_zip/data/ed438b8b276d0169131523969f4e3582/datapackage_zip.zip

## Tasks

* [ ] ~~accept `content_type` argument in `Processing artifact` https://github.com/datahq/planner/blob/master/planner/nodes/base_processing_node.py#L12~~
* [ ] ~~set them in proccessing nodes~~ 
* [ ] ~~yield it with other info (title, deps etc...) from `nodes/planner`~~
* [x] guess file type by extention via [mimetypes](https://docs.python.org/3.6/library/mimetypes.html)  and pass to `dump.to_s3` via `dump_steps` #

## Analysis

While trying to refactor here occurs that it's not that easy to get resource name. While it's very simple while `dump.to_s3` so will fix there

**Comment by akariv** [comment]
Perhaps we could start by using the [mimetypes](https://docs.python.org/3.6/library/mimetypes.html) builtin library which returns mime types for most common file extensions.
wdyt?

**Comment by zelima** [comment]
Sure, simpler=better

**Comment by zelima** [comment]
FIXED in frictionlessdata/datapackage-pipelines-aws#12

**Comment by zelima** [comment]
For some reasons, this is still an issue. See analysis

**Comment by zelima** [comment]
Closing as FIXED. Files on S3 are pushed fine. Something goes wrong when requesting same files from Cloudflare. See followup here https://github.com/datahq/pm/issues/101
