### ISSUE TITLE
Changes for NonTabularProcessingNode

### ISSUE THREAD

**Issue by zelima** [datahq/planner#29]
we've introduced new processor for updating source metadata. see https://github.com/datahq/assembler/issues/93

Need to updated planner appropriately 

## Acceptance Criteria 

* [x] tests are fine 

## Tasks

* [ ] update `output_nodes` (zip) - add `deduplicate_processors`
* [ ] update `node_collectors` - move `NonTabularProcessingNode` before zip
* [ ] update meta for `NonTabularProcessingNode`

**Comment by zelima** [comment]
Non-tabular node is now renamed to `OriginalProcessingNode` and is responsible for both `original` and `source/tabular` resources. It does nothing but copies the resource as were. 

Due to changes we've introduced new resource with type original. This one is placed in `archive` folder and is suffixed with `_original`
