### ISSUE TITLE
No need of duplicated resources in zip and final dp.json 

### ISSUE THREAD

**Issue by zelima** [datahq/planner#40]
originally coming from here https://github.com/datahq/datahub-qa/issues/152

So we don't need `source/tabular` in zip and `original` in live datapackage.json (unless it's resource is non-tabular). 

## Acceptance Criteria

* [x] no duplicates on after `data get dataset`
* [x] no duplicate rsources in dp.json

## Tasks

* [x] refactor to skip source/tabular in `OutputToZipProcessingNode`
* [x] refactor `OriginalProcessingNode` to handle exluding original taular source 
  * ~~maybe bring back `source/non-tabulr`?~~ We just do not include original if a source/tabular presents 
* [x] update tests in assembler
* [x] update tests in specstore

**Comment by zelima** [comment]
FIXED
