### ISSUE TITLE
Processing steps are ignored in case of they are multiple

### ISSUE THREAD

**Issue by zelima** [datahq/planner#42]
If you try and push Eg excel files with 2 sheets only one sheet will be processed as rest is ignored

## Acceptance Criteria

* [x] all processing steps are applied 

## Tasks

* [x] Investigate reason 
* [x] add test case in BB tests for assembler
* [x] fix the bug

**Comment by zelima** [comment]
FIXED
