### ISSUE TITLE
Add English name to each processing node

### ISSUE THREAD

**Issue by zelima** [datahq/planner#9]
We need nice English names for pipelines, so that frontend could use it in a best way.

## Acceptance Criteria

* [x] Each pipeline has nice English title

## Tasks 

* [x] Decide on names
  * Creating CSV
  * Creating JSON
  * Creating ZIP
  * Generating views
  * Validating package contents
  * Copying source data
  * Creating Package - for main pipeline [@zelima: what does "for main pipeline mean" I'm not sure i'd know as a user ~rufus]
* [x] do analysis
* [x] Changes in planner (see analaysis) 

## Analysis 

* Add `title` property to `ProcessingArtifact` class:
```
class ProcessingArtifact():
    def __init__(self,
                 datahub_type,
                 resource_name,
                 required_streamed_artifacts: List['ProcessingArtifact'],
                 required_other_artifacts: List['ProcessingArtifact'],
                 pipeline_steps,
                 streamable
                 title="Create DataSet"):
```

* Pass from each processing node title of the pipeline eg in basic_nodes:  `ProcessingArtifact(..., title=Creating CSV file)` 
* yield `derived_artifact.title` together with `derived_artifact.resource_name, pipeline_steps, dependencies` from `nodes/planer`  https://github.com/datahq/planner/blob/master/planner/nodes/planner.py#L175
* add `title` property to pipeline details together with `pipelines`, `hooks`, `dependencies`   https://github.com/datahq/planner/blob/master/planner/planner.py#L74

n the update API it will be the part of `pipeline_details` - it will be top-level property:
```
{
  dependencies: [...]
  hooks: []
  title: some title
}
```

**Comment by akariv** [comment]
Please just add a comment on how specstore will know the pipeline name in the `update` API.
I think that present progressive is better (i.e. 'Creating CSV file' instead of 'Create CSV file' @rufuspollock wdyt)

**Comment by zelima** [comment]
@rufuspollock You do not need to know what the main pipeline is as a user - it will say `Create dataset` that's all you need to know as a user - that creation of dataset failed. The "main pipeline" is behind the scenes

@akariv I agree with present progressive
@akariv ~~In the update API it will be the part of `pipeline_details` - it will be top-level property:~~
```
{
  dependencies: [...]
  hooks: []
  title: some title
}
```

**Comment by zelima** [comment]
@akariv thinking more about this - I Think I will need new column in the pipelines table "title" and will store it there. 

After that, I will be able to query DB and get title via pipeline iD - wdyt?

**Comment by zelima** [comment]
FIXED. Done in the way that previous comment says
